In [1]:
import numpy as np
array = np.arange(16).reshape(4,4)
print(array)
print("\n1st and 2nd element in 2nd and 3rd row\n",array[1:3,0:2])
print("\n2nd and 3rd element in 1st row\n",array[:1,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

1st and 2nd element in 2nd and 3rd row
 [[4 5]
 [8 9]]

2nd and 3rd element in 1st row
 [[1 2]]
